# Generated by Django 4.2.7 on 2025-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='meeting_type',
            field=models.CharField(choices=[('ONLINE', 'Online Meeting'), ('PHYSICAL', 'Physical Meeting')], default='ONLINE', max_length=10),
        ),
    ]
