# Generated by Django 4.2.7 on 2025-03-24 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('astrologers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='specializations',
            field=models.ManyToManyField(related_name='astrologers', to='astrologers.specialization'),
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='astrologer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='astrologeravailability',
            name='astrologer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='astrologers.astrologerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('astrologer', 'customer')},
        ),
        migrations.AlterUniqueTogether(
            name='astrologeravailability',
            unique_together={('astrologer', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
